---
require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - bin/*
    - spec/dummy_app/**/*

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/ArgumentsForwarding:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Layout/LineLength:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

# FIXME
RSpec/MultipleMemoizedHelpers:
  Enabled: false

# FIXME
RSpec/MessageSpies:
  Enabled: false

# FIXME
RSpec/SubjectStub:
  Enabled: false
